{
 "title": "Open-Metadata",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "OMD Web App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server Latency Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(increase(latency_requests_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.75, sum(increase(latency_requests_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "75th"
    },
    {
     "expr": "histogram_quantile(0.5, sum(increase(latency_requests_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "50th"
    },
    {
     "expr": "histogram_quantile(0.1, sum(increase(latency_requests_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "10th"
    }
   ]
  },
  {
   "title": "Slowest URI's (Top 5)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(5, histogram_quantile(0.95, sum(increase(http_server_requests_seconds_bucket\n[$__rate_interval])) by (le, uri)))",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  { "title": "Elastic Search", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "ES Response Type Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    { "expr": "aws_es_2xx_sum", "legendFormat": "2xx" },
    { "expr": "aws_es_3xx_sum", "legendFormat": "3xx" },
    { "expr": "aws_es_4xx_sum", "legendFormat": "4xx" },
    { "expr": "aws_es_5xx_sum", "legendFormat": "5xx" }
   ]
  },
  {
   "title": "Elastic Search Space ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(aws_es_cluster_used_space_sum)",
     "legendFormat": "USED"
    },
    {
     "expr": "with(\n  free = max(aws_es_free_storage_space_sum),\n  used = sum(aws_es_cluster_used_space_sum)\n  ) free + used",
     "legendFormat": "TOTAL"
    }
   ]
  },
  {
   "title": "ES Cluster Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "aws_es_cluster_status_green_average",
     "legendFormat": "Green"
    },
    {
     "expr": "aws_es_cluster_status_red_average",
     "legendFormat": "Red"
    },
    {
     "expr": "aws_es_cluster_status_yellow_average",
     "legendFormat": "Yellow"
    }
   ]
  },
  { "title": "RDS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "DB CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(aws_rds_cpuutilization_maximum)",
     "legendFormat": "Utilization"
    }
   ]
  },
  {
   "title": "DB Max Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(aws_rds_read_latency_maximum)",
     "legendFormat": "Read"
    },
    {
     "expr": "max(aws_rds_write_latency_maximum)",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "DB Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "max(aws_rds_database_connections_maximum)",
     "legendFormat": "{{dimension_Role}}"
    }
   ]
  }
 ]
}